org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.caching=true
org.gradle.parallel=true
gradle.cache.push=false

## Parchment
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17


mod_name=Forager's Insight
mod_id=foragersinsight
mod_version=1.0.0

minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.244
neo_version_range=[21.1.0,)
loader_version_range=[4,)
blueprint_version=8397829
farmersdelight_version=8083481
jei_minecraft=1.21
jei_version=19.8.2.99