modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/template-mod/issues"
license = "https://github.com/team-abnormals/template-mod/blob/main/LICENSE.txt"

[[mods]]
    modId = "foragersinsight"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "minecraft:dirt"
    configBackground = "minecraft:textures/block/dirt.png"
    authors = "tiomadre"
    credits = "tiomadre"
    displayURL = ""
    displayName = "Forager's Insight"
    description = ''' A foraging expansion for Farmer's Delight!'''

[[dependencies.foragersinsight]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.20.2)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.foragersinsight]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.3,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.foragersinsight]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[7.1.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.foragersinsight]]
    modId = "farmersdelight"
    mandatory = true
    versionRange = "[1.2.0,)"
    ordering = "AFTER"
    side = "BOTH"